---
# variables required to standup satellite
rhn_user: "admin"
rhn_password: "CHANGEME"
rhn_activation_key: "rhel-7-satellite"
rhn_org_id: "1"
rhn_org: "CHANGEME"
dhcp_gw: "192.168.1.1"
dhcp_range: "192.168.1.240 192.168.1.250"
dhcp_start: "192.168.1.240"
dhcp_end: "192.168.1.250"
dns_server: "10.42.0.254"
dns_zone: "xana.du"
dns_rev_zone: "1.42.10.in-addr.arpa"
subnet_name: "192.168.1.x"
subnet_nw: "192.168.1.0"
subnet_mask: "255.255.255.0"
mgmt_int: "eth0"
satellite_admin: "admin"
satellite_password: "CHANGEME"
satellite_domain: "CHANGEME"
satellite_ip: "192.168.1.205"
satellite_location: "CHANGEME"
satellite_org: "CHANGEME"
satellite_puppet_env: "production"
satellite_ak: "rhel-7-osp"
ntp_server: "CHANGEME"
libvirt_host: "CHANGEME"
ospd_nw_name: "ospd"
ospd_nw: "192.168.100.0"
ospd_nw_mask: "255.255.255.0"
ospd_nw_gw: "192.168.100.1"
ospd_nw_start: "192.168.100.240"
ospd_nw_end: "192.168.100.250"
ospd_host: "ospd"
opsd_ip: "192.168.1.241"
ospd_nm: "255.255.255.0"

# repos
repos:
  rhel-7-ks:
    product: "Red Hat Enterprise Linux Server"
    name: "Red Hat Enterprise Linux 7 Server (Kickstart)"
    releasever: "7.2"
    basearch: "x86_64"
  rhel-7-base:
    product: "Red Hat Enterprise Linux Server"
    name: "Red Hat Enterprise Linux 7 Server (RPMs)"
    releasever: "7Server"
    basearch: "x86_64"
  rhel-7-common:
    product: "Red Hat Enterprise Linux Server"
    name: "Red Hat Enterprise Linux 7 Server - RH Common (RPMs)"
    releasever: "7Server"
    basearch: "x86_64"
  rhel-7-optional:
    product: "Red Hat Enterprise Linux Server"
    name: "Red Hat Enterprise Linux 7 Server - Optional (RPMs)"
    releasever: "7Server"
    basearch: "x86_64"
  rhel-7-supplementary:
    product: "Red Hat Enterprise Linux Server"
    name: "Red Hat Enterprise Linux 7 Server - Supplementary (RPMs)"
    releasever: "7Server"
    basearch: "x86_64"
#  rhel-7-extras:
#    product: "Red Hat Enterprise Linux Server"
#    name: "Red Hat Enterprise Linux 7 Server - Extras (RPMs)"
#    releasever: "7Server"
#    basearch: "x86_64"
#  rhel-7-satellite-tools:
#    product: "Red Hat Enterprise Linux Server"
#    name: "Red Hat Satellite Tools 6.1 (for RHEL 7 Server) (RPMs)"
#    releasever: "7Server"
#    basearch: "x86_64"
  rhel-7-openstack:
    product: "Red Hat OpenStack"
    name: "Red Hat Enterprise Linux OpenStack Platform 7.0 for RHEL 7 (RPMs)"
    releasever: "7Server"
    basearch: "x86_64"
  rhel-7-openstack-director:
    product: "Red Hat OpenStack"
    name: "Red Hat Enterprise Linux OpenStack Platform 7.0 director for RHEL 7 (RPMs)"
    releasever: "7Server"
    basearch: "x86_64"
  rhel-7-scl:
    product: "Red Hat Software Collections for RHEL Server"
    name: "Red Hat Software Collections RPMs for Red Hat Enterprise Linux 7 Server"
    releasever: "7Server"
    basearch: "x86_64"
